# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

DISABLE_MAGIC_FUNCTIONS=true

plugins=(
	colored-man-pages 
	colorize 
	command-not-found 
	extract
	git-auto-fetch
	git-extras
	thefuck 
	zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

path+=(
    $HOME/.local/bin
    $HOME/go/bin
)

eval $(thefuck --alias)

source $HOME/.env.zsh
source $HOME/.aliases.zsh
source $HOME/.functions.zsh
source $HOME/.config/cheat/cheat.zsh
[ -f ~/.gec.zsh ] && source  ~/.gec.zsh

### Function path -> maybe?
# fpath+=("${HOME}/.zsh_functions")

setopt glob_dots # Do not require a leading ‘.’ in a filename to be matched explicitly.
