# Path to your oh-my-zsh installation.
export ZSH="${HOME}/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"

DISABLE_MAGIC_FUNCTIONS=true

plugins=(
	colored-man-pages 
	colorize 
	command-not-found 
	extract
	git-auto-fetch
	git-extras
	#thefuck
	zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

path+=(
    $HOME/.local/bin
    $HOME/go/bin
)

bindkey '^[[1;3C' forward-word
bindkey '^[[1;3D' backward-word
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[5C' forward-word
bindkey '^[[5D' backward-word
bindkey '^[^[[C' forward-word
bindkey '^[^[[D' backward-word

# press ctrl + y to copy current line to buffer/clipboard
cmd_to_clip () { wl-copy -n <<< $BUFFER }
zle -N cmd_to_clip
bindkey '^Y' cmd_to_clip


if [ -f /etc/private.true ]; then
    source <(kubectl completion zsh)
fi

# PYENV
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

source $HOME/.env.zsh
source $HOME/.aliases.zsh
source $HOME/.functions.zsh
source $HOME/.config/cheat/cheat.zsh
[ -f ~/.gec.zsh ] && source  ~/.gec.zsh

### Function path -> maybe?
# fpath+=("${HOME}/.zsh_functions")

setopt glob_dots # Do not require a leading ‘.’ in a filename to be matched explicitly.
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

eval $(thefuck --alias)
